-- Flóra tudástára: az ESPEN és ECCO irányelvek desztillált, magyar nyelvű ajánlásai.
-- Saját megfogalmazás; a forrás és az evidenciafokozat hivatkozásként szerepel.
-- Futtatás: Supabase Dashboard -> SQL Editor -> beilleszt -> Run.

delete from public.flora_knowledge;

insert into public.flora_knowledge (source, source_ref, topic, grade, content) values
  ('ESPEN 2019', 'Recommendation 1', 'kockazat', '0', 'Gyümölcsben és zöldségben gazdag, n-3 zsírsavakban gazdag és n-6 zsírsavakban szegény étrend csökkenti a Crohn-betegség és a colitis ulcerosa kialakulásának kockázatát.'),
  ('ESPEN 2019', 'Recommendation 2', 'kockazat', '0', 'Az ultrafeldolgozott élelmiszerek és az ipari emulgeálószerek (például karboximetil-cellulóz) növelhetik az IBD kockázatát, ezért kerülésük általánosan javasolható.'),
  ('ESPEN 2019', 'Recommendation 2b', 'kockazat', 'B', 'A szoptatás javasolt: a csecsemő optimális tápláléka, és csökkenti az IBD későbbi kialakulásának kockázatát.'),
  ('ESPEN 2019', 'Recommendation 3A', 'szures', 'GPP', 'Az IBD-betegek alultápláltsági kockázatnak vannak kitéve, ezért a diagnóziskor és utána rendszeresen szűrni kell őket.'),
  ('ESPEN 2019', 'Recommendation 3B', 'szures', 'GPP', 'Az igazolt alultápláltságot kezelni kell, mert rontja a betegség lefolyását, növeli a szövődmények arányát és rontja az életminőséget.'),
  ('ESPEN 2019', 'Recommendation 28', 'szures', 'GPP', 'Remisszióban is javasolt a dietetikai tanácsadás, hogy elkerülhető legyen az alultápláltság és a táplálkozással összefüggő zavarok.'),
  ('ESPEN 2019', 'Recommendation 4', 'energia_feherje', 'GPP', 'Az IBD-betegek energiaigénye általában megegyezik az egészséges népességével.'),
  ('ESPEN 2019', 'Recommendation 5A', 'energia_feherje', 'GPP', 'Aktív betegségben a fehérjeigény megnő: felnőtteknél 1,2–1,5 gramm testsúlykilogrammonként naponta.'),
  ('ESPEN 2019', 'Recommendation 5B', 'energia_feherje', 'GPP', 'Remisszióban a fehérjeigény nem emelkedett, felnőtteknél körülbelül 1 gramm testsúlykilogrammonként naponta elegendő.'),
  ('ESPEN 2019', 'Recommendation 6', 'mikrotapanyag', 'GPP', 'Az IBD-betegeknél rendszeresen ellenőrizni kell a mikrotápanyag-hiányokat, és a kimutatott hiányt pótolni kell.'),
  ('ESPEN 2019', 'Recommendation 7A', 'mikrotapanyag', 'A', 'Vashiányos vérszegénység esetén vaspótlás javasolt; a cél a hemoglobinszint és a vasraktárak normalizálása.'),
  ('ESPEN 2019', 'Recommendation 7B', 'mikrotapanyag', 'A', 'Enyhe vérszegénységnél, klinikailag inaktív betegség mellett a szájon át szedhető vas az elsőként választandó, ha a beteg korábban jól tolerálta.'),
  ('ESPEN 2019', 'Recommendation 7C', 'mikrotapanyag', 'A', 'Intravénás vaspótlás jön szóba aktív betegségnél, korábbi orális vas-intolerancia esetén, vagy ha a hemoglobin 100 g/l alatt van. Erről az orvos dönt.'),
  ('ESPEN 2019', 'Recommendation 11', 'mikrotapanyag', 'B', 'Aktív betegségben és szteroidkezelés alatt ellenőrizni kell a szérum kalcium- és 25(OH)-D-vitamin-szintet, és szükség esetén pótolni kell a csontsűrűség csökkenésének megelőzésére.'),
  ('ESPEN 2019', 'Recommendation 34', 'mikrotapanyag', 'A', 'Ha a csípőbél végső szakaszából több mint 20 centimétert eltávolítottak, B12-vitamin-pótlás szükséges.'),
  ('ESPEN 2019', 'Recommendation 35', 'mikrotapanyag', 'B', 'Szulfaszalazin- vagy metotrexát-kezelés mellett folsav (B9-vitamin) pótlása javasolt.'),
  ('ESPEN 2019', 'Recommendation 12B', 'mikrotapanyag', 'GPP', 'Hiperoxaluria esetén gyakran zsírfelszívódási zavar is fennáll; ilyenkor célzott dietetikai tanácsadás szükséges.'),
  ('ESPEN 2019', 'Recommendation 8', 'fellangolas', 'GPP', 'Nincs olyan általánosan ajánlható IBD-diéta, amely aktív betegségben önmagában remissziót idézne elő.'),
  ('ESPEN 2019', 'Recommendation 13', 'fellangolas', 'GPP', 'Kizárásos diéták nem javasoltak aktív Crohn-betegségben a remisszió eléréséhez, még egyéni ételintoleranciák mellett sem.'),
  ('ESPEN 2019', 'Recommendation 10', 'fellangolas', 'GPP', 'Bélszűkület és elzáródásos panaszok esetén módosított állagú, pépesebb és rostszegényebb étrend javasolt.'),
  ('ESPEN 2019', 'Recommendation 9', 'fellangolas', '0', 'A Crohn-betegséghez felszívódási és emésztési zavar társulhat, amit a dietetikai tanácsadásnak figyelembe kell vennie.'),
  ('ESPEN 2019', 'Recommendation 19', 'fellangolas', 'GPP', 'Törekedni kell a kiszáradás elkerülésére; Crohn-betegségben ez a trombózis kockázatát is csökkenti.'),
  ('ESPEN 2019', 'Recommendation 29', 'remisszio', '0', 'Remisszióban nem szükséges speciális diétát követni.'),
  ('ESPEN 2019', 'Recommendation 29b', 'remisszio', 'GPP', 'Remisszióban a szokásos, kiegyensúlyozott étrend a javasolt, a tápláltsági állapot rendszeres figyelemmel kísérése mellett.'),
  ('ESPEN 2019', 'Recommendation 31', 'remisszio', '0', 'A nem célzott, magas rosttartalmú étrend általában nem javasolt a remisszió fenntartására.'),
  ('ESPEN 2019', 'Recommendation 30', 'remisszio', 'B', 'Az n-3 zsírsav-kiegészítés nem javasolt a remisszió fenntartására.'),
  ('ESPEN 2019', 'Recommendation 4b', 'mozgas_testsuly', '0', 'Túlsúlyos IBD-betegeknél a fogyókúra csak stabil remisszióban javasolt, az általános elhízás-irányelvek szerint.'),
  ('ESPEN 2019', 'Recommendation 3c', 'mozgas_testsuly', 'GPP', 'Minden IBD-betegnél javasolt az állóképességi edzés. Csökkent izomtömeg vagy izomteljesítmény esetén célzott mozgásprogram ajánlott.'),
  ('ESPEN 2019', 'Recommendation 16', 'een', 'B', 'Gyermekeknél és serdülőknél aktív Crohn-betegségben a kizárólagos enterális táplálás (EEN) hatékony, és elsőként választandó a remisszió eléréséhez.'),
  ('ESPEN 2019', 'Recommendation 1b', 'een', 'B', 'Gyermekeknél enyhe-közepes Crohn-betegségben a Crohn-kizárásos diéta részleges enterális táplálással alternatívája lehet a kizárólagos enterális táplálásnak.'),
  ('ESPEN 2019', 'Recommendation 1c', 'een', '0', 'Felnőtteknél enyhe-közepes aktív Crohn-betegségben a Crohn-kizárásos diéta megfontolható, enterális táplálással vagy anélkül.'),
  ('ESPEN 2019', 'Recommendation 15A', 'een', '0', 'Ha táplálásterápia szükséges, az első lépés a szájon át szedhető tápszer, a normál étkezés kiegészítéseként.'),
  ('ESPEN 2019', 'Recommendation 33', 'een', 'GPP', 'Remisszióban lévő Crohn-betegeknél tápszer vagy enterális táplálás javasolt, ha az alultápláltság dietetikai tanácsadással nem kezelhető megfelelően.'),
  ('ESPEN 2019', 'Recommendation 18B', 'een', 'B', 'Speciális összetevők, például glutamin vagy n-3 zsírsavak, nem javasoltak az enterális táplálásban IBD-ben.'),
  ('ESPEN 2019', 'Recommendation 14A', 'probiotikum', '0', 'Enyhe-közepes colitis ulcerosában a remisszió eléréséhez megfontolható Lactobacillus reuteri vagy többtörzsű probiotikum.'),
  ('ESPEN 2019', 'Recommendation 14B', 'probiotikum', 'B', 'Probiotikum nem javasolt aktív Crohn-betegség kezelésére, sem a visszaesés megelőzésére.'),
  ('ESPEN 2019', 'Recommendation 32A', 'probiotikum', 'B', 'Colitis ulcerosában a remisszió fenntartására megfontolható probiotikum.'),
  ('ESPEN 2019', 'Recommendation 32B', 'probiotikum', '0', 'Crohn-betegségben a remisszió fenntartására nem javasolt probiotikum.'),
  ('ESPEN 2019', 'Recommendation 5', 'probiotikum', 'B', 'A prebiotikum nem javasolt sem Crohn-betegségben, sem colitis ulcerosában, sem aktív szakaszban, sem a remisszió fenntartására.'),
  ('ESPEN 2019', 'Recommendation 33A', 'probiotikum', 'B', 'Pouchitisben, ha az antibiotikum-kezelés nem vált be, többtörzsű probiotikum jöhet szóba. Erről az orvos dönt.'),
  ('ESPEN 2019', 'Recommendation 36', 'terhesseg', 'GPP', 'Terhesség alatt rendszeresen ellenőrizni kell a vas- és folsavszintet, és hiány esetén pótolni kell.'),
  ('ESPEN 2019', 'Recommendation 37', 'terhesseg', 'GPP', 'Szoptatás alatt rendszeresen ellenőrizni kell a tápláltsági állapotot, és hiány esetén pótolni kell.'),
  ('ECCO 2026', 'Statement 40', 'orvosi_temak', null, 'Az immunszuppresszív kezelés megkezdése előtt, lehetőleg már a diagnóziskor, érdemes átnézni az orvossal az oltottsági állapotot és a fertőzési kockázatokat.'),
  ('ECCO 2026', 'Statement 42-47', 'orvosi_temak', null, 'Immunszuppresszív kezelés mellett szóba jövő oltások: hepatitis A és B, évenkénti influenza, pneumococcus, HPV és rekombináns övsömör elleni oltás. Az élő kórokozót tartalmazó oltások külön mérlegelést igényelnek, ezekről mindig az orvos dönt.'),
  ('ECCO 2026', 'Statement 17-19', 'orvosi_temak', null, 'Anti-TNF vagy JAK-gátló kezelés megkezdése előtt tuberkulózis-szűrés szükséges, magas kockázat esetén évente ismételve.'),
  ('ECCO 2026', 'Statement 15-16', 'orvosi_temak', null, 'Immunszuppresszív kezelés alatt álló nőknél fontos az életkornak megfelelő méhnyakszűrés, HPV-teszttel kiegészítve.'),
  ('ECCO 2026', 'Statement 32-33', 'orvosi_temak', null, 'Fellángoláskor javasolt kizárni a bélfertőzést, különösen a Clostridioides difficile fertőzést, mielőtt a kezelést módosítanák.'),
  ('ECCO 2026', 'Statement 34', 'orvosi_temak', null, 'Utazás előtt, különösen trópusi célpont esetén, érdemes orvossal egyeztetni az oltásokról és a megelőzésről.'),
  ('ESPEN 2019', 'Recommendation 9A', 'fellangolas', 'GPP', 'Súlyos hasmenés, illetve nagy váladékozású ileo- vagy jejunosztóma esetén követni kell a folyadékvesztést és a vizelet nátriumszintjét. Ilyenkor a hipotóniás folyadék (például tiszta víz) csökkentése és sóoldat növelése javasolt, az egyéni ételintoleranciák figyelembevételével.'),
  ('ESPEN 2019', 'Recommendation 25', 'een', 'B', 'Colitis ulcerosában a táplálásterápia (enterális vagy parenterális) sem felnőtteknél, sem gyermekeknél nem elsődleges kezelés.'),
  ('ESPEN 2019', 'Recommendation 38', 'een', '0', 'Colitis ulcerosában a parenterális táplálás általában nem indokolt, kivéve ha a beteg más módon nem táplálható megfelelően.'),
  ('ESPEN 2019', 'Recommendation 40', 'een', 'GPP', 'Sem az enterális, sem a parenterális táplálás nem elsődleges terápia a remisszió fenntartására IBD-ben.'),
  ('ESPEN 2019', 'Recommendation 15B', 'een', 'A', 'Ha a szájon át történő táplálkozás nem elegendő, az enterális táplálás (szondatáplálás) élvez elsőbbséget a parenterálissal szemben, hacsak az nem ellenjavallt.'),
  ('ESPEN 2019', 'Recommendation 45', 'een', 'GPP', 'Ha a szükséglet több mint hét napon át sem szájon át, sem enterálisan nem fedezhető legalább 50 százalékban, akkor az enterális és parenterális táplálás kombinációja javasolt. Ez kórházi ellátás keretében történik.'),
  ('ESPEN 2019', 'Recommendation 41', 'fellangolas', 'B', 'Műtét előtt nem indokolt az éjféltől kezdődő teljes koplalás; a korszerű gyakorlat rövidebb éhezési időt alkalmaz. A konkrét előírást mindig a műtétet végző csapat adja meg.'),
  ('ESPEN 2019', 'Recommendation 12A', 'mikrotapanyag', 'GPP', 'Epesavmegkötő kezelés (például kolesztiramin) mellett nem szükséges más táplálkozás, mint a többi Crohn-betegnél; ez önmagában nem növeli érdemben a zsírfelszívódási zavart.'),
  ('ESPEN 2019', 'Table 1', 'mikrotapanyag', null, 'A pótlandó összes vasmennyiséget az orvos a hemoglobinszint és a testsúly alapján számolja ki: minél alacsonyabb a hemoglobin és minél nagyobb a testsúly, annál nagyobb a hiányzó mennyiség. Ez orvosi számítás, nem önállóan beállítandó adag.'),
  ('ESPEN 2019', 'Recommendation 53', 'probiotikum', '0', 'Colitis ulcerosában, ha az 5-ASA készítményt a beteg nem tolerálja, egyes probiotikumok alternatívát jelenthetnek az enyhe betegség kezelésében. Erről az orvos dönt.'),
  ('ESPEN 2019', 'Recommendation 54', 'probiotikum', '0', 'Pouchitis megelőzésére többtörzsű probiotikum megfontolható.'),
  ('ESPEN 2019', 'Recommendation 57', 'probiotikum', 'GPP', 'Pouchitisben a prebiotikumok használatáról nem lehet ajánlást megfogalmazni, mert nincs elég bizonyíték.'),
  ('ESPEN 2019', 'Recommendation 58', 'gyogyszer_hatarok', '0', 'Nincs olyan általánosan ajánlható antibiotikum-kezelés, amely aktív Crohn-betegségben vagy a remisszió fenntartásában bevált volna.'),
  ('ESPEN 2019', 'Recommendation 59', 'gyogyszer_hatarok', '0', 'Colitis ulcerosában sem aktív betegségben, sem a remisszió fenntartására nem javasolható általánosan antibiotikum-kezelés.'),
  ('ESPEN 2019', 'Recommendation 60', 'gyogyszer_hatarok', '0', 'Akut pouchitisben antibiotikum jöhet szóba elsőként; a készítmény megválasztása orvosi döntés.'),
  ('ESPEN 2019', 'Recommendation 14', 'szures', 'GPP', 'Az IBD-ellátásban a szakápoló kulcsszerepet játszik, beleértve a tápláltsági szűrést és az étrendi támogatást is. Érdemes tőle is kérdezni.'),
  ('ECCO 2026', 'Statement 2', 'orvosi_temak', null, 'A diagnózis felállításakor javasolt a hepatitis B, hepatitis C, HIV és Epstein-Barr-vírus szerológiai szűrése, még az immunszuppresszív kezelés megkezdése előtt.'),
  ('ECCO 2026', 'Statement 41', 'orvosi_temak', null, 'Élő kórokozót tartalmazó oltás beadása előtt az immunszuppresszív kezelés leállítása után legalább egy hónap várakozás javasolt. Az időzítésről az orvos dönt.'),
  ('ECCO 2026', 'Statement 1', 'orvosi_temak', null, 'Az immunszuppresszív kezelés önmagában nem jelent általánosan megnövekedett fertőzéskockázatot; ez a konkrét készítménytől és a beteg állapotától függ.'),
  ('ECCO 2026', 'Statement 38-39', 'orvosi_temak', null, 'Sem az idős kor, sem a törékenység nem zárja ki önmagában az immunszuppresszív kezelést; ezt egyénileg kell mérlegelni az orvossal.'),
  ('ECCO 2026', 'Statement 36', 'orvosi_temak', null, 'Az IBD-betegek, az immunszuppresszív kezelés alatt állók is, nem tűnnek fogékonyabbnak a maláriára vagy más trópusi betegségre, és a lefolyás sem súlyosabb náluk.'),
  ('ECCO 2026', 'Statement 11', 'orvosi_temak', null, 'Súlyos vagy kezelésre nem reagáló colitis ulcerosa esetén az orvos vizsgálhatja a citomegalovírus-fertőzés lehetőségét is.'),
  ('ECCO 2026', 'Statement 13', 'orvosi_temak', null, 'Epstein-Barr-vírusra negatív betegeknél a tiopurin típusú szerek mellett magasabb a limfóma kockázata; ezt a kezelés megválasztásakor az orvos figyelembe veszi.'),
  ('ECCO 2026', 'Statement 33', 'orvosi_temak', null, 'Immunszuppresszív kezelés alatt fellángoláskor székletvizsgálat javasolt a gyakori bélkórokozók kizárására.'),
  ('ECCO 2026', 'Statement 30', 'orvosi_temak', null, 'Endémiás területről érkező betegeknél érdemes lehet Strongyloides stercoralis szerológiai vizsgálat az immunszuppresszív kezelés előtt.'),
  ('ECCO 2026', 'Table 4', 'orvosi_temak', null, 'Minden oltásnál az az alapelv, hogy lehetőleg még az immunszuppresszív kezelés megkezdése előtt adják be. Ilyenkor alakul ki a legjobb védettség.'),
  ('ECCO 2026', 'Table 4', 'orvosi_temak', null, 'Immunszuppresszív kezelés alatt a hepatitis B elleni oltásra adott válasz gyengébb, körülbelül 60 százalék. Ezért az oltás után ellenanyagszint-ellenőrzés javasolt, hogy kiderüljön, kialakult-e a védettség.'),
  ('ECCO 2026', 'Table 4', 'orvosi_temak', null, 'Hepatitis A elleni oltás után egy-két hónappal érdemes ellenőrizni a védettséget. Ha kialakult, rutinszerű emlékeztető oltás általában nem szükséges.'),
  ('ECCO 2026', 'Table 4', 'orvosi_temak', null, 'A HPV elleni oltás 26 éves korig ajánlott; e felett a pótlás általában nem indokolt, 45 év felett pedig nem javasolt.'),
  ('ECCO 2026', 'Table 4', 'orvosi_temak', null, 'Immunszuppresszív kezelés alatt álló IBD-betegeknek pneumococcus elleni oltás javasolt, konjugált oltással kezdve. Bizonyos oltástípus után öt év múlva ismétlés jöhet szóba.');
